# The URL the site will be built for
base_url = "https://kaug-radio.web.app" # "https://kaug.org"

title = "KAUG Radio & Concert Promotion"
description = "Welcome to KAUG!"
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "even"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
# Put all your custom variables here
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/events", name = "Events"},
    {url = "$BASE_URL/shows", name = "Shows"},
    {url = "$BASE_URL/artists", name = "Artists"},
    {url = "$BASE_URL/about", name = "About"},
]
even_title = "/res/icon.svg"
katex_auto_render = true
katex_enable = true
